version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "${PROJECT_NAME}"
    environment:
      DB_USER: "${DB_USER}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_HOST: "fundpayment-db-1"
      DB_PORT: 5432
      ENVIRONMENT : "stg"
    ports:
      - "${WEB_EXPORT}:8000"
    command: >
      sh -c "./shell/start.sh"
    depends_on:
      - db
    volumes:
      - "./:/home/FundPayment"
      - "./staticfiles:/home/FundPayment/staticfiles"
      - "./shell:/home/FundPayment/shell"
    restart: always

  db:
    image: postgres:15.1-alpine
    ports:
      - "${DB_EXPORT}:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PGDATA: "/var/lib/postgresql/data/${PROJECT_NAME}"
    volumes:
      - "db_volume:/var/lib/postgresql/data/${PROJECT_NAME}"
      - "./shell/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh"
    restart: always

volumes:
  db_volume:
